# See README.md for purpose.
services:
  mygazebo:
    build: .
    image: robo-gazebo
    # For passing GUI through to windows:
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/wslg:/mnt/wslg
    environment:
      - DISPLAY
      - WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR
      - PULSE_SERVER
  # gui:
  #   # "Build the dockerfile in this directory and call it this name"
  #   build: .
  #   image: robo-turtlesim-docker-gui
  #   # For passing GUI through to windows:
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix
  #     - /mnt/wslg:/mnt/wslg
  #   environment:
  #     - DISPLAY
  #     - WAYLAND_DISPLAY
  #     - XDG_RUNTIME_DIR
  #     - PULSE_SERVER
  # teleop:
  #   image: robo-turtlesim-docker-gui
  #   stdin_open: true # docker run -i
  #   tty: true        # docker run -t
  #   command: ros2 run turtlesim turtle_teleop_key
  # rqt:
  #   image: robo-turtlesim-docker-gui
  #   command: rqt
  #   # For passing GUI through to windows:
  #   volumes:
  #     - /tmp/.X11-unix:/tmp/.X11-unix
  #     - /mnt/wslg:/mnt/wslg
  #   environment:
  #     - DISPLAY
  #     - WAYLAND_DISPLAY
  #     - XDG_RUNTIME_DIR
  #     - PULSE_SERVER