# See README.md for purpose.
services:
  mygazebo:
    build: .
    image: robo-sim
    # For passing GUI through to windows:
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/wslg:/mnt/wslg
    environment:
      - DISPLAY
      - WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR
      - PULSE_SERVER
  gazebo-ros-bridge:
    build: .
    image: robo-sim 
    command: /bin/bash -c "source /opt/ros/humble/setup.bash && ros2 run ros_gz_bridge parameter_bridge /model/vehicle_blue/cmd_vel@geometry_msgs/msg/Twist]ignition.msgs.Twist"
  