services:

  slamopencl:
    build: . 
    image: unit000a
    network_mode: host
    ipc: host
    stdin_open: true
    tty: true
    stop_grace_period: 1s
    volumes:
      - ${PWD}/:/pwd
      - $XAUTHORITY:/root/.Xauthority
    command: /bin/bash -c "cd /pwd/ && cmake -S . -B build && cd build && make && ./SLAMHost"
    environment:
      - DISPLAY
      - WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR
      - PULSE_SERVER
