# See README.md for purpose.
services:
  gui:
    # "Build the dockerfile in this directory and call it this name"
    build: .
    image: robo-turtlesim-docker-gui
    # For passing GUI through to windows:
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/wslg:/mnt/wslg
    environment:
      - DISPLAY
      - WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR
      - PULSE_SERVER
  teleop:
    image: robo-turtlesim-docker-gui
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    # "ros2", "run", "turtlesim", "turtle_teleop_key"
    command: ros2 run turtlesim turtle_teleop_key